### ISSUE TITLE
Weekly resets for portainer environments

### ISSUE THREAD

**Issue by nathanieloon** [openeyes/Docker#4]
It would be nice to have a weekly reset option (as well as the nightly/weekly timings) for portainer OE containers.

**Comment by nathanieloon** [comment]
@biskyt also have a local branch for this as well.

**Comment by biskyt** [comment]
No problem. I've added weekly and monthly options to all the templates.

If you set your template URL in the portainer settings to the following then the changes will show immediately.. Otherwise you would need to grab the template file and manually add it to the portainer container.

https://raw.githubusercontent.com/openeyes/Docker/master/portainer/templates/openeyes-templates.json
